import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/ui/Header";
import { SpaceGrostek } from "@/fonts/font";

export const metadata: Metadata = {
  title: "Assignment-Anurag",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${SpaceGrostek.className} bg-gray-100`}>
        <Header />
        {children}
      </body>
    </html>
  );
}

// ,weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
